/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/home`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/instructions`; params?: Router.UnknownInputParams; } | { pathname: `/inventory`; params?: Router.UnknownInputParams; } | { pathname: `/NavBar`; params?: Router.UnknownInputParams; } | { pathname: `/portion`; params?: Router.UnknownInputParams; } | { pathname: `/recipe`; params?: Router.UnknownInputParams; } | { pathname: `/../app copy/home`; params?: Router.UnknownInputParams; } | { pathname: `/../app copy/index`; params?: Router.UnknownInputParams; } | { pathname: `/../app copy/instructions`; params?: Router.UnknownInputParams; } | { pathname: `/../app copy/inventory`; params?: Router.UnknownInputParams; } | { pathname: `/../app copy/NavBar`; params?: Router.UnknownInputParams; } | { pathname: `/../app copy/portion`; params?: Router.UnknownInputParams; } | { pathname: `/../app copy/recipe`; params?: Router.UnknownInputParams; } | { pathname: `/Settings`; params?: Router.UnknownInputParams; } | { pathname: `/../../screens/homeScreen`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/home`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/instructions`; params?: Router.UnknownOutputParams; } | { pathname: `/inventory`; params?: Router.UnknownOutputParams; } | { pathname: `/NavBar`; params?: Router.UnknownOutputParams; } | { pathname: `/portion`; params?: Router.UnknownOutputParams; } | { pathname: `/recipe`; params?: Router.UnknownOutputParams; } | { pathname: `/../app copy/home`; params?: Router.UnknownOutputParams; } | { pathname: `/../app copy/index`; params?: Router.UnknownOutputParams; } | { pathname: `/../app copy/instructions`; params?: Router.UnknownOutputParams; } | { pathname: `/../app copy/inventory`; params?: Router.UnknownOutputParams; } | { pathname: `/../app copy/NavBar`; params?: Router.UnknownOutputParams; } | { pathname: `/../app copy/portion`; params?: Router.UnknownOutputParams; } | { pathname: `/../app copy/recipe`; params?: Router.UnknownOutputParams; } | { pathname: `/Settings`; params?: Router.UnknownOutputParams; } | { pathname: `/../../screens/homeScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/home${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/instructions${`?${string}` | `#${string}` | ''}` | `/inventory${`?${string}` | `#${string}` | ''}` | `/NavBar${`?${string}` | `#${string}` | ''}` | `/portion${`?${string}` | `#${string}` | ''}` | `/recipe${`?${string}` | `#${string}` | ''}` | `/../app copy/home${`?${string}` | `#${string}` | ''}` | `/../app copy/index${`?${string}` | `#${string}` | ''}` | `/../app copy/instructions${`?${string}` | `#${string}` | ''}` | `/../app copy/inventory${`?${string}` | `#${string}` | ''}` | `/../app copy/NavBar${`?${string}` | `#${string}` | ''}` | `/../app copy/portion${`?${string}` | `#${string}` | ''}` | `/../app copy/recipe${`?${string}` | `#${string}` | ''}` | `/Settings${`?${string}` | `#${string}` | ''}` | `/../../screens/homeScreen${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/home`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/instructions`; params?: Router.UnknownInputParams; } | { pathname: `/inventory`; params?: Router.UnknownInputParams; } | { pathname: `/NavBar`; params?: Router.UnknownInputParams; } | { pathname: `/portion`; params?: Router.UnknownInputParams; } | { pathname: `/recipe`; params?: Router.UnknownInputParams; } | { pathname: `/../app copy/home`; params?: Router.UnknownInputParams; } | { pathname: `/../app copy/index`; params?: Router.UnknownInputParams; } | { pathname: `/../app copy/instructions`; params?: Router.UnknownInputParams; } | { pathname: `/../app copy/inventory`; params?: Router.UnknownInputParams; } | { pathname: `/../app copy/NavBar`; params?: Router.UnknownInputParams; } | { pathname: `/../app copy/portion`; params?: Router.UnknownInputParams; } | { pathname: `/../app copy/recipe`; params?: Router.UnknownInputParams; } | { pathname: `/Settings`; params?: Router.UnknownInputParams; } | { pathname: `/../../screens/homeScreen`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
    }
  }
}
